# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
