# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
