# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160305_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_short',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
